# Generated by Django 3.2 on 2021-04-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_auto_20210409_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='material_label',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
